### 服务器配置
server:
  port: 8080
  
  ### TIMO配置
project:
  captcha-open: false                         #是否开启登录验证码
  shiro:
    remember-me-timeout: 7                    #cookie记住登录信息时间，默认7天（天）
    global-session-timeout: 1800              #Session会话超时时间，默认30分钟（秒）
  upload:
    #file-path:                               #文件上传路径，默认在项目根目录upload下
    static-path: /upload/**                   #上传文件静态访问路径
  
### spring配置
spring:
## 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:1039/timo?useSSL=false&characterEncoding=utf-8
    username: root
    password: thzzc0926
    
#mybatis-plus
  mybatis-plus:  
    mapper-locations: classpath:com/ithzzc/cloud/modules/system/mapper/xml/*.xml
    type-aliases-package: com.ithzzc.cloud.modules.system.entity
    configuration: 
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
  
    ## thymeleaf模板设置
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false